
/*
 * Created on 19 oct. 2014 ( Time 18:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.jee.mock;

import java.util.LinkedList;
import java.util.List;

import fr.jee.model.jpa.RencontresEntity;
import fr.jee.mock.tool.MockValues;

public class RencontresEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public RencontresEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public RencontresEntity createInstance( Integer idevent ) {
		RencontresEntity entity = new RencontresEntity();
		// Init Primary Key fields
		entity.setIdevent( idevent) ;
		// Init Data fields
		// Init Link fields (if any)
		// setUsers( TODO ) ; // Users 
		// setEvents( TODO ) ; // Events 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<RencontresEntity> createList(int count) {
		List<RencontresEntity> list = new LinkedList<RencontresEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
