
/*
 * Created on 20 oct. 2014 ( Time 17:03:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.jee.mock;

import java.util.LinkedList;
import java.util.List;

import fr.jee.model.jpa.UsersEntity;
import fr.jee.mock.tool.MockValues;

public class UsersEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UsersEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UsersEntity createInstance( Integer id ) {
		UsersEntity entity = new UsersEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setMail( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setPasswd( mockValues.nextString(100) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfEvents( TODO ) ; // List<Events> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UsersEntity> createList(int count) {
		List<UsersEntity> list = new LinkedList<UsersEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
