/*
 * Created on 19 oct. 2014 ( Time 18:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.jee.test.persistence;


import fr.jee.model.jpa.RencontresEntity;
import fr.jee.mock.RencontresEntityMock;
import fr.jee.persistence.PersistenceServiceProvider;
import fr.jee.persistence.services.RencontresPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Rencontres persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class RencontresPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		RencontresPersistence service = PersistenceServiceProvider.getService(RencontresPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Rencontres persistence : delete + load ..." );
		
		RencontresPersistence service = PersistenceServiceProvider.getService(RencontresPersistence.class);
		
		RencontresEntityMock mock = new RencontresEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(RencontresPersistence service, RencontresEntityMock mock, Integer idevent ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		RencontresEntity entity = service.load( idevent );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( idevent ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Users
			// . Events
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( idevent );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
