/*
 * Created on 19 oct. 2014 ( Time 18:44:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package fr.jee.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import fr.jee.model.jpa.RencontresEntity;
import fr.jee.persistence.commons.jpa.GenericJpaService;
import fr.jee.persistence.commons.jpa.JpaOperation;
import fr.jee.persistence.services.RencontresPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Rencontres" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class RencontresPersistenceJPA extends GenericJpaService<RencontresEntity, Integer> implements RencontresPersistence {

	/**
	 * Constructor
	 */
	public RencontresPersistenceJPA() {
		super(RencontresEntity.class);
	}

	@Override
	public RencontresEntity load( Integer idevent ) {
		return super.load( idevent );
	}

	@Override
	public boolean delete( Integer idevent ) {
		return super.delete( idevent );
	}

	@Override
	public boolean delete(RencontresEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdevent() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("RencontresEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
