/*
 * Created on 20 oct. 2014 ( Time 18:20:27 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package fr.jee.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "EVENTS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="EVENTS", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EventsEntity.countAll", query="SELECT COUNT(x) FROM EventsEntity x" )
} )
public class EventsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", nullable=false, length=255)
    private String     nom          ;

    @Column(name="ACTIF", nullable=false)
    private Integer    actif        ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATEDEBUT", nullable=false)
    private Date       datedebut    ;

    @Temporal(TemporalType.TIME)
    @Column(name="HEUREDEBUT", nullable=false)
    private Date       heuredebut   ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATEFIN", nullable=false)
    private Date       datefin      ;

    @Temporal(TemporalType.TIME)
    @Column(name="HEUREFIN", nullable=false)
    private Date       heurefin     ;

	// "idcreateur" (column "IDCREATEUR") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="events", targetEntity=ParticipantsEntity.class)
    private List<ParticipantsEntity> listOfParticipants;

    @ManyToOne
    @JoinColumn(name="IDCREATEUR", referencedColumnName="ID")
    private UsersEntity users       ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EventsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : ACTIF ( INTEGER ) 
    public void setActif( Integer actif ) {
        this.actif = actif;
    }
    public Integer getActif() {
        return this.actif;
    }

    //--- DATABASE MAPPING : DATEDEBUT ( DATE ) 
    public void setDatedebut( Date datedebut ) {
        this.datedebut = datedebut;
    }
    public Date getDatedebut() {
        return this.datedebut;
    }

    //--- DATABASE MAPPING : HEUREDEBUT ( TIME ) 
    public void setHeuredebut( Date heuredebut ) {
        this.heuredebut = heuredebut;
    }
    public Date getHeuredebut() {
        return this.heuredebut;
    }

    //--- DATABASE MAPPING : DATEFIN ( DATE ) 
    public void setDatefin( Date datefin ) {
        this.datefin = datefin;
    }
    public Date getDatefin() {
        return this.datefin;
    }

    //--- DATABASE MAPPING : HEUREFIN ( TIME ) 
    public void setHeurefin( Date heurefin ) {
        this.heurefin = heurefin;
    }
    public Date getHeurefin() {
        return this.heurefin;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfParticipants( List<ParticipantsEntity> listOfParticipants ) {
        this.listOfParticipants = listOfParticipants;
    }
    public List<ParticipantsEntity> getListOfParticipants() {
        return this.listOfParticipants;
    }

    public void setUsers( UsersEntity users ) {
        this.users = users;
    }
    public UsersEntity getUsers() {
        return this.users;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(actif);
        sb.append("|");
        sb.append(datedebut);
        sb.append("|");
        sb.append(heuredebut);
        sb.append("|");
        sb.append(datefin);
        sb.append("|");
        sb.append(heurefin);
        return sb.toString(); 
    } 

}
