/*
 * Created on 20 oct. 2014 ( Time 18:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  


package fr.jee.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "PARTICIPANTS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="PARTICIPANTS", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ParticipantsEntity.countAll", query="SELECT COUNT(x) FROM ParticipantsEntity x" )
} )
public class ParticipantsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private ParticipantsEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", nullable=false, length=100)
    private String     nom          ;

    @Column(name="PRENOM", nullable=false, length=100)
    private String     prenom       ;

    @Column(name="SOCIETE", nullable=false, length=255)
    private String     societe      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="IDEVENT", referencedColumnName="ID", insertable=false, updatable=false)
    private EventsEntity events      ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ParticipantsEntity() {
		super();
		this.compositePrimaryKey = new ParticipantsEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setIdevent( Integer idevent ) {
        this.compositePrimaryKey.setIdevent( idevent ) ;
    }
    public Integer getIdevent() {
        return this.compositePrimaryKey.getIdevent() ;
    }
    public void setMail( String mail ) {
        this.compositePrimaryKey.setMail( mail ) ;
    }
    public String getMail() {
        return this.compositePrimaryKey.getMail() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : PRENOM ( VARCHAR ) 
    public void setPrenom( String prenom ) {
        this.prenom = prenom;
    }
    public String getPrenom() {
        return this.prenom;
    }

    //--- DATABASE MAPPING : SOCIETE ( VARCHAR ) 
    public void setSociete( String societe ) {
        this.societe = societe;
    }
    public String getSociete() {
        return this.societe;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setEvents( EventsEntity events ) {
        this.events = events;
    }
    public EventsEntity getEvents() {
        return this.events;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(prenom);
        sb.append("|");
        sb.append(societe);
        return sb.toString(); 
    } 

}
