/*
 * Created on 27 oct. 2014 ( Time 17:10:26 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package fr.jee.model.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ParticipantsEntity" ( stored in table "PARTICIPANTS" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ParticipantsEntityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="IDEVENT", nullable=false)
    private Integer    idevent      ;
    
    @Column(name="MAIL", nullable=false, length=255)
    private String     mail         ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ParticipantsEntityKey() {
        super();
    }

    public ParticipantsEntityKey( Integer idevent, String mail ) {
        super();
        this.idevent = idevent ;
        this.mail = mail ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setIdevent( Integer value ) {
        this.idevent = value;
    }
    public Integer getIdevent() {
        return this.idevent;
    }

    public void setMail( String value ) {
        this.mail = value;
    }
    public String getMail() {
        return this.mail;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ParticipantsEntityKey other = (ParticipantsEntityKey) obj; 
		//--- Attribute idevent
		if ( idevent == null ) { 
			if ( other.idevent != null ) 
				return false ; 
		} else if ( ! idevent.equals(other.idevent) ) 
			return false ; 
		//--- Attribute mail
		if ( mail == null ) { 
			if ( other.mail != null ) 
				return false ; 
		} else if ( ! mail.equals(other.mail) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idevent
		result = prime * result + ((idevent == null) ? 0 : idevent.hashCode() ) ; 
		//--- Attribute mail
		result = prime * result + ((mail == null) ? 0 : mail.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(idevent); 
		sb.append("|"); 
		sb.append(mail); 
        return sb.toString();
    }
}
