/*
 * Created on 27 oct. 2014 ( Time 17:10:26 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package fr.jee.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import fr.jee.model.jpa.ParticipantsEntity;
import fr.jee.model.jpa.ParticipantsEntityKey;
import fr.jee.persistence.commons.jpa.GenericJpaService;
import fr.jee.persistence.commons.jpa.JpaOperation;
import fr.jee.persistence.services.ParticipantsPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Participants" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ParticipantsPersistenceJPA extends GenericJpaService<ParticipantsEntity, ParticipantsEntityKey> implements ParticipantsPersistence {

	/**
	 * Constructor
	 */
	public ParticipantsPersistenceJPA() {
		super(ParticipantsEntity.class);
	}

	@Override
	public ParticipantsEntity load( Integer idevent, String mail ) {
		// Build the composite key
		ParticipantsEntityKey key = new ParticipantsEntityKey( idevent, mail );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer idevent, String mail ) {
		// Build the composite key
		ParticipantsEntityKey key = new ParticipantsEntityKey( idevent, mail );
		return super.delete( key );
	}

	@Override
	public boolean delete(ParticipantsEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			ParticipantsEntityKey key = new ParticipantsEntityKey( entity.getIdevent(), entity.getMail() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ParticipantsEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
